version: "3.9"
 
services: # adds 2 services: mysql and phpmyadmin to connect with
  mysql: 
    container_name: mysql 
    platform: linux/x86_64
    build: ./database/
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: 
      - ./database/local.env
    volumes:
      - my-db:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d
    ports:
      - '3306:3306'
    networks:
      - mynetwork
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  phpmyadmin:
    container_name: phpmyadmin
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - ./local.env 
    tty: true
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  # ubuntu:
  #   image: ubuntu:latest
  #   container_name: ubuntu
  #   # restart: always
  #   tty: true
  #   networks:
  #     - mynetwork

  # ubuntu:
  #   container_name: ubuntu
  #   # restart: always
  #   platform: linux/x86_64
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   tty: true
  #   networks:
  #     - mynetwork
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

networks:
  mynetwork:
    driver: bridge
 
volumes: # add persistent data even if container is removed.
  my-db: