# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Repos\License-Plate-Recognizer-GitHub\gui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LPR_App(object):
    def setupUi(self, LPR_App):
        LPR_App.setObjectName("LPR_App")
        LPR_App.resize(1440, 841)
        self.verticalLayoutWidget = QtWidgets.QWidget(LPR_App)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 621, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.WebCamStreamLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.WebCamStreamLayout.setContentsMargins(0, 0, 0, 0)
        self.WebCamStreamLayout.setObjectName("WebCamStreamLayout")
        self.WebCamStreamLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.WebCamStreamLabel.setObjectName("WebCamStreamLabel")
        self.WebCamStreamLayout.addWidget(self.WebCamStreamLabel)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(LPR_App)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 420, 621, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.ProcessLogLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.ProcessLogLayout.setContentsMargins(0, 0, 0, 0)
        self.ProcessLogLayout.setObjectName("ProcessLogLayout")
        self.ProcessLogLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ProcessLogLabel.setObjectName("ProcessLogLabel")
        self.ProcessLogLayout.addWidget(self.ProcessLogLabel)
        self.ProcessLogListWidget = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.ProcessLogListWidget.setObjectName("ProcessLogListWidget")
        self.ProcessLogLayout.addWidget(self.ProcessLogListWidget)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(LPR_App)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(780, 10, 641, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalLayoutWidget_4.sizePolicy().hasHeightForWidth())
        self.verticalLayoutWidget_4.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.ReadingLPLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.ReadingLPLayout.setContentsMargins(0, 0, 0, 0)
        self.ReadingLPLayout.setObjectName("ReadingLPLayout")
        self.ReadingLPLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReadingLPLabel.sizePolicy().hasHeightForWidth())
        self.ReadingLPLabel.setSizePolicy(sizePolicy)
        self.ReadingLPLabel.setObjectName("ReadingLPLabel")
        self.ReadingLPLayout.addWidget(self.ReadingLPLabel)
        self.ReadingLPTextBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_4)
        self.ReadingLPTextBrowser.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReadingLPTextBrowser.sizePolicy().hasHeightForWidth())
        self.ReadingLPTextBrowser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ReadingLPTextBrowser.setFont(font)
        self.ReadingLPTextBrowser.setObjectName("ReadingLPTextBrowser")
        self.ReadingLPLayout.addWidget(self.ReadingLPTextBrowser)
        self.StartReadingButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.StartReadingButton.setObjectName("StartReadingButton")
        self.ReadingLPLayout.addWidget(self.StartReadingButton)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(LPR_App)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(780, 420, 641, 401))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.MatchingVehicleInfoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.MatchingVehicleInfoLayout.setContentsMargins(0, 0, 0, 0)
        self.MatchingVehicleInfoLayout.setObjectName("MatchingVehicleInfoLayout")
        self.MatchingVehicleInfoLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.MatchingVehicleInfoLabel.setObjectName("MatchingVehicleInfoLabel")
        self.MatchingVehicleInfoLayout.addWidget(self.MatchingVehicleInfoLabel)
        self.MatchingVehicleInfoTextBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.MatchingVehicleInfoTextBrowser.setFont(font)
        self.MatchingVehicleInfoTextBrowser.setObjectName("MatchingVehicleInfoTextBrowser")
        self.MatchingVehicleInfoLayout.addWidget(self.MatchingVehicleInfoTextBrowser)
        self.MatchingVehicleInfoPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.MatchingVehicleInfoPushButton.setObjectName("MatchingVehicleInfoPushButton")
        self.MatchingVehicleInfoLayout.addWidget(self.MatchingVehicleInfoPushButton)

        self.retranslateUi(LPR_App)
        QtCore.QMetaObject.connectSlotsByName(LPR_App)

    def retranslateUi(self, LPR_App):
        _translate = QtCore.QCoreApplication.translate
        LPR_App.setWindowTitle(_translate("LPR_App", "Form"))
        self.WebCamStreamLabel.setText(_translate("LPR_App", "Web Cam:"))
        self.ProcessLogLabel.setText(_translate("LPR_App", "İşlem Günlüğü:"))
        self.ReadingLPLabel.setText(_translate("LPR_App", "Okunan Plaka:"))
        self.StartReadingButton.setText(_translate("LPR_App", "Başlat"))
        self.MatchingVehicleInfoLabel.setText(_translate("LPR_App", "Eşleşen Kayıt Bilgileri:"))
        self.MatchingVehicleInfoPushButton.setText(_translate("LPR_App", "Göster"))
