# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Repos\License-Plate-Recognizer-GitHub\gui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LPR_App(object):
    def setupUi(self, LPR_App):
        LPR_App.setObjectName("LPR_App")
        LPR_App.resize(1296, 921)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LPR_App.sizePolicy().hasHeightForWidth())
        LPR_App.setSizePolicy(sizePolicy)
        LPR_App.setStyleSheet("background-color: #252525")
        self.GroupBoxPreviousPlates = QtWidgets.QGroupBox(LPR_App)
        self.GroupBoxPreviousPlates.setGeometry(QtCore.QRect(20, 10, 541, 721))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.GroupBoxPreviousPlates.setFont(font)
        self.GroupBoxPreviousPlates.setStyleSheet("color: #e4f1fe")
        self.GroupBoxPreviousPlates.setObjectName("GroupBoxPreviousPlates")
        self.tableViewPreviousPlates = QtWidgets.QTableView(self.GroupBoxPreviousPlates)
        self.tableViewPreviousPlates.setGeometry(QtCore.QRect(20, 40, 491, 651))
        self.tableViewPreviousPlates.setObjectName("tableViewPreviousPlates")
        self.GroupBoxPassIcons = QtWidgets.QGroupBox(LPR_App)
        self.GroupBoxPassIcons.setGeometry(QtCore.QRect(20, 740, 541, 171))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.GroupBoxPassIcons.setFont(font)
        self.GroupBoxPassIcons.setStyleSheet("color: #e4f1fe")
        self.GroupBoxPassIcons.setObjectName("GroupBoxPassIcons")
        self.LabelRegisteredHeader = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelRegisteredHeader.setGeometry(QtCore.QRect(30, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelRegisteredHeader.setFont(font)
        self.LabelRegisteredHeader.setObjectName("LabelRegisteredHeader")
        self.LabelUnrecognizedHeader = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelUnrecognizedHeader.setGeometry(QtCore.QRect(130, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelUnrecognizedHeader.setFont(font)
        self.LabelUnrecognizedHeader.setObjectName("LabelUnrecognizedHeader")
        self.LabelGuestHeader = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelGuestHeader.setGeometry(QtCore.QRect(440, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelGuestHeader.setFont(font)
        self.LabelGuestHeader.setObjectName("LabelGuestHeader")
        self.LabelBlackListedHeader = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelBlackListedHeader.setGeometry(QtCore.QRect(300, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelBlackListedHeader.setFont(font)
        self.LabelBlackListedHeader.setObjectName("LabelBlackListedHeader")
        self.LabelRegisteredIcon = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelRegisteredIcon.setGeometry(QtCore.QRect(30, 90, 50, 50))
        self.LabelRegisteredIcon.setText("")
        self.LabelRegisteredIcon.setObjectName("LabelRegisteredIcon")
        self.LabelUnrecognizedIcon = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelUnrecognizedIcon.setGeometry(QtCore.QRect(150, 90, 50, 50))
        self.LabelUnrecognizedIcon.setText("")
        self.LabelUnrecognizedIcon.setObjectName("LabelUnrecognizedIcon")
        self.LabelGuestIcon = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelGuestIcon.setGeometry(QtCore.QRect(440, 90, 50, 50))
        self.LabelGuestIcon.setText("")
        self.LabelGuestIcon.setObjectName("LabelGuestIcon")
        self.LabelBlackListedIcon = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelBlackListedIcon.setGeometry(QtCore.QRect(310, 90, 50, 50))
        self.LabelBlackListedIcon.setText("")
        self.LabelBlackListedIcon.setObjectName("LabelBlackListedIcon")
        self.GroupBoxReadingLP = QtWidgets.QGroupBox(LPR_App)
        self.GroupBoxReadingLP.setGeometry(QtCore.QRect(590, 470, 681, 201))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.GroupBoxReadingLP.setFont(font)
        self.GroupBoxReadingLP.setStyleSheet("color: #e4f1fe")
        self.GroupBoxReadingLP.setObjectName("GroupBoxReadingLP")
        self.ButtonStartReading = QtWidgets.QPushButton(self.GroupBoxReadingLP)
        self.ButtonStartReading.setGeometry(QtCore.QRect(520, 70, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.ButtonStartReading.setFont(font)
        self.ButtonStartReading.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ButtonStartReading.setMouseTracking(True)
        self.ButtonStartReading.setStyleSheet("background-color: #454545;\n"
"color: #e4f1fe;")
        self.ButtonStartReading.setObjectName("ButtonStartReading")
        self.LabelReadingLPText = QtWidgets.QLabel(self.GroupBoxReadingLP)
        self.LabelReadingLPText.setGeometry(QtCore.QRect(140, 40, 351, 70))
        font = QtGui.QFont()
        font.setPointSize(38)
        self.LabelReadingLPText.setFont(font)
        self.LabelReadingLPText.setText("")
        self.LabelReadingLPText.setObjectName("LabelReadingLPText")
        self.LabelReadingLPIcon = QtWidgets.QLabel(self.GroupBoxReadingLP)
        self.LabelReadingLPIcon.setGeometry(QtCore.QRect(30, 40, 70, 70))
        self.LabelReadingLPIcon.setText("")
        self.LabelReadingLPIcon.setObjectName("LabelReadingLPIcon")
        self.ProgressBarReadingCountdown = QtWidgets.QProgressBar(self.GroupBoxReadingLP)
        self.ProgressBarReadingCountdown.setGeometry(QtCore.QRect(30, 150, 461, 23))
        self.ProgressBarReadingCountdown.setAutoFillBackground(False)
        self.ProgressBarReadingCountdown.setStyleSheet("QProgressBar {\n"
"     border: 2px solid #252525;\n"
"     border-radius: 5px;\n"
"     background-color: #252525;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: #1C6F8D;\n"
"     width: 20px;\n"
" }")
        self.ProgressBarReadingCountdown.setProperty("value", 0)
        self.ProgressBarReadingCountdown.setTextVisible(False)
        self.ProgressBarReadingCountdown.setFormat("")
        self.ProgressBarReadingCountdown.setObjectName("ProgressBarReadingCountdown")
        self.GroupBoxWebcamCapture = QtWidgets.QGroupBox(LPR_App)
        self.GroupBoxWebcamCapture.setGeometry(QtCore.QRect(590, 20, 681, 431))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.GroupBoxWebcamCapture.setFont(font)
        self.GroupBoxWebcamCapture.setStyleSheet("color: #e4f1fe")
        self.GroupBoxWebcamCapture.setObjectName("GroupBoxWebcamCapture")
        self.LabelWebcamFrame = QtWidgets.QLabel(self.GroupBoxWebcamCapture)
        self.LabelWebcamFrame.setGeometry(QtCore.QRect(20, 40, 641, 371))
        self.LabelWebcamFrame.setAutoFillBackground(False)
        self.LabelWebcamFrame.setStyleSheet("QLabel {\n"
"    background-color:  #454545;\n"
"}")
        self.LabelWebcamFrame.setText("")
        self.LabelWebcamFrame.setObjectName("LabelWebcamFrame")
        self.GroupBoxMatchingVehicleInfo = QtWidgets.QGroupBox(LPR_App)
        self.GroupBoxMatchingVehicleInfo.setGeometry(QtCore.QRect(590, 690, 681, 221))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.GroupBoxMatchingVehicleInfo.setFont(font)
        self.GroupBoxMatchingVehicleInfo.setStyleSheet("color: #e4f1fe")
        self.GroupBoxMatchingVehicleInfo.setObjectName("GroupBoxMatchingVehicleInfo")
        self.LabelLPHeader = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelLPHeader.setGeometry(QtCore.QRect(30, 40, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.LabelLPHeader.setFont(font)
        self.LabelLPHeader.setObjectName("LabelLPHeader")
        self.LabelBLStatusHeader = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelBLStatusHeader.setGeometry(QtCore.QRect(30, 85, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.LabelBLStatusHeader.setFont(font)
        self.LabelBLStatusHeader.setObjectName("LabelBLStatusHeader")
        self.LabelRegisterStatusHeader = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelRegisterStatusHeader.setGeometry(QtCore.QRect(30, 130, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.LabelRegisterStatusHeader.setFont(font)
        self.LabelRegisterStatusHeader.setObjectName("LabelRegisterStatusHeader")
        self.LabelLPText = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelLPText.setGeometry(QtCore.QRect(230, 40, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelLPText.setFont(font)
        self.LabelLPText.setText("")
        self.LabelLPText.setObjectName("LabelLPText")
        self.LabelBLStatusText = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelBLStatusText.setGeometry(QtCore.QRect(230, 130, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelBLStatusText.setFont(font)
        self.LabelBLStatusText.setText("")
        self.LabelBLStatusText.setObjectName("LabelBLStatusText")
        self.LabelRegisterStatusText = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelRegisterStatusText.setGeometry(QtCore.QRect(230, 90, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelRegisterStatusText.setFont(font)
        self.LabelRegisterStatusText.setText("")
        self.LabelRegisterStatusText.setObjectName("LabelRegisterStatusText")
        self.ButtonQueryVehicleInfoInDB = QtWidgets.QPushButton(self.GroupBoxMatchingVehicleInfo)
        self.ButtonQueryVehicleInfoInDB.setGeometry(QtCore.QRect(520, 50, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.ButtonQueryVehicleInfoInDB.setFont(font)
        self.ButtonQueryVehicleInfoInDB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ButtonQueryVehicleInfoInDB.setMouseTracking(True)
        self.ButtonQueryVehicleInfoInDB.setStyleSheet("background-color: #454545;\n"
"color: #e4f1fe;")
        self.ButtonQueryVehicleInfoInDB.setObjectName("ButtonQueryVehicleInfoInDB")
        self.ButtonInsertNewVehicle = QtWidgets.QPushButton(self.GroupBoxMatchingVehicleInfo)
        self.ButtonInsertNewVehicle.setGeometry(QtCore.QRect(520, 110, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.ButtonInsertNewVehicle.setFont(font)
        self.ButtonInsertNewVehicle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ButtonInsertNewVehicle.setMouseTracking(True)
        self.ButtonInsertNewVehicle.setStyleSheet("background-color: #454545;\n"
"color: #e4f1fe;")
        self.ButtonInsertNewVehicle.setObjectName("ButtonInsertNewVehicle")
        self.LabelNotificationMesssage = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelNotificationMesssage.setGeometry(QtCore.QRect(90, 170, 561, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.LabelNotificationMesssage.setFont(font)
        self.LabelNotificationMesssage.setText("")
        self.LabelNotificationMesssage.setObjectName("LabelNotificationMesssage")
        self.LabelLabelNotificationMesssageIcon = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelLabelNotificationMesssageIcon.setGeometry(QtCore.QRect(40, 170, 30, 30))
        self.LabelLabelNotificationMesssageIcon.setText("")
        self.LabelLabelNotificationMesssageIcon.setObjectName("LabelLabelNotificationMesssageIcon")

        self.retranslateUi(LPR_App)
        QtCore.QMetaObject.connectSlotsByName(LPR_App)

    def retranslateUi(self, LPR_App):
        _translate = QtCore.QCoreApplication.translate
        LPR_App.setWindowTitle(_translate("LPR_App", "Form"))
        self.GroupBoxPreviousPlates.setTitle(_translate("LPR_App", "Önceki Plakalar"))
        self.GroupBoxPassIcons.setTitle(_translate("LPR_App", "Geçiş İkonları"))
        self.LabelRegisteredHeader.setText(_translate("LPR_App", "Kayıtlı"))
        self.LabelUnrecognizedHeader.setText(_translate("LPR_App", "Tanınmayan"))
        self.LabelGuestHeader.setText(_translate("LPR_App", "Misafir"))
        self.LabelBlackListedHeader.setText(_translate("LPR_App", "Kara Liste"))
        self.GroupBoxReadingLP.setTitle(_translate("LPR_App", "Okunan Plaka"))
        self.ButtonStartReading.setText(_translate("LPR_App", "Başlat"))
        self.GroupBoxWebcamCapture.setTitle(_translate("LPR_App", "Kamera Görüntüsü"))
        self.GroupBoxMatchingVehicleInfo.setTitle(_translate("LPR_App", "Eşleşen Kayıt"))
        self.LabelLPHeader.setText(_translate("LPR_App", "Plaka: "))
        self.LabelBLStatusHeader.setText(_translate("LPR_App", "Kayıt Durumu:"))
        self.LabelRegisterStatusHeader.setText(_translate("LPR_App", "Kara Liste Durumu:"))
        self.ButtonQueryVehicleInfoInDB.setText(_translate("LPR_App", "Sorgula"))
        self.ButtonInsertNewVehicle.setText(_translate("LPR_App", "Yeni Kayıt"))
