# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Repos\License-Plate-Recognizer-GitHub\gui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LPR_App(object):
    def setupUi(self, LPR_App):
        LPR_App.setObjectName("LPR_App")
        LPR_App.resize(1271, 921)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LPR_App.sizePolicy().hasHeightForWidth())
        LPR_App.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        LPR_App.setFont(font)
        LPR_App.setStyleSheet("background-color: #252525")
        self.GroupBoxPreviousPlates = QtWidgets.QGroupBox(LPR_App)
        self.GroupBoxPreviousPlates.setGeometry(QtCore.QRect(20, 10, 531, 721))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.GroupBoxPreviousPlates.setFont(font)
        self.GroupBoxPreviousPlates.setStyleSheet("color: #e4f1fe")
        self.GroupBoxPreviousPlates.setObjectName("GroupBoxPreviousPlates")
        self.TableViewPreviousPlates = QtWidgets.QTableView(self.GroupBoxPreviousPlates)
        self.TableViewPreviousPlates.setGeometry(QtCore.QRect(20, 40, 491, 661))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.TableViewPreviousPlates.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.TableViewPreviousPlates.setFont(font)
        self.TableViewPreviousPlates.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TableViewPreviousPlates.setMouseTracking(True)
        self.TableViewPreviousPlates.setFocusPolicy(QtCore.Qt.TabFocus)
        self.TableViewPreviousPlates.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.TableViewPreviousPlates.setToolTip("")
        self.TableViewPreviousPlates.setWhatsThis("")
        self.TableViewPreviousPlates.setAccessibleName("")
        self.TableViewPreviousPlates.setStyleSheet("QIcon {\n"
"    margin: 0% 30%\n"
"}")
        self.TableViewPreviousPlates.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TableViewPreviousPlates.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TableViewPreviousPlates.setLineWidth(3)
        self.TableViewPreviousPlates.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.TableViewPreviousPlates.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TableViewPreviousPlates.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.TableViewPreviousPlates.setDragDropOverwriteMode(False)
        self.TableViewPreviousPlates.setAlternatingRowColors(False)
        self.TableViewPreviousPlates.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TableViewPreviousPlates.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TableViewPreviousPlates.setIconSize(QtCore.QSize(50, 50))
        self.TableViewPreviousPlates.setTextElideMode(QtCore.Qt.ElideNone)
        self.TableViewPreviousPlates.setShowGrid(True)
        self.TableViewPreviousPlates.setGridStyle(QtCore.Qt.NoPen)
        self.TableViewPreviousPlates.setCornerButtonEnabled(False)
        self.TableViewPreviousPlates.setObjectName("TableViewPreviousPlates")
        self.TableViewPreviousPlates.horizontalHeader().setVisible(True)
        self.TableViewPreviousPlates.horizontalHeader().setDefaultSectionSize(162)
        self.TableViewPreviousPlates.horizontalHeader().setHighlightSections(False)
        self.TableViewPreviousPlates.horizontalHeader().setMinimumSectionSize(162)
        self.TableViewPreviousPlates.horizontalHeader().setStretchLastSection(True)
        self.TableViewPreviousPlates.verticalHeader().setVisible(False)
        self.TableViewPreviousPlates.verticalHeader().setCascadingSectionResizes(False)
        self.TableViewPreviousPlates.verticalHeader().setDefaultSectionSize(80)
        self.TableViewPreviousPlates.verticalHeader().setHighlightSections(False)
        self.TableViewPreviousPlates.verticalHeader().setMinimumSectionSize(80)
        self.GroupBoxPassIcons = QtWidgets.QGroupBox(LPR_App)
        self.GroupBoxPassIcons.setGeometry(QtCore.QRect(20, 740, 531, 171))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.GroupBoxPassIcons.setFont(font)
        self.GroupBoxPassIcons.setStyleSheet("color: #e4f1fe")
        self.GroupBoxPassIcons.setObjectName("GroupBoxPassIcons")
        self.LabelRegisteredHeader = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelRegisteredHeader.setGeometry(QtCore.QRect(30, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelRegisteredHeader.setFont(font)
        self.LabelRegisteredHeader.setObjectName("LabelRegisteredHeader")
        self.LabelUnrecognizedHeader = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelUnrecognizedHeader.setGeometry(QtCore.QRect(130, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelUnrecognizedHeader.setFont(font)
        self.LabelUnrecognizedHeader.setObjectName("LabelUnrecognizedHeader")
        self.LabelGuestHeader = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelGuestHeader.setGeometry(QtCore.QRect(440, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelGuestHeader.setFont(font)
        self.LabelGuestHeader.setObjectName("LabelGuestHeader")
        self.LabelBlackListedHeader = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelBlackListedHeader.setGeometry(QtCore.QRect(300, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelBlackListedHeader.setFont(font)
        self.LabelBlackListedHeader.setObjectName("LabelBlackListedHeader")
        self.LabelRegisteredIcon = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelRegisteredIcon.setGeometry(QtCore.QRect(30, 90, 50, 50))
        self.LabelRegisteredIcon.setText("")
        self.LabelRegisteredIcon.setObjectName("LabelRegisteredIcon")
        self.LabelUnrecognizedIcon = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelUnrecognizedIcon.setGeometry(QtCore.QRect(150, 90, 50, 50))
        self.LabelUnrecognizedIcon.setText("")
        self.LabelUnrecognizedIcon.setObjectName("LabelUnrecognizedIcon")
        self.LabelGuestIcon = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelGuestIcon.setGeometry(QtCore.QRect(440, 90, 50, 50))
        self.LabelGuestIcon.setText("")
        self.LabelGuestIcon.setObjectName("LabelGuestIcon")
        self.LabelBlackListedIcon = QtWidgets.QLabel(self.GroupBoxPassIcons)
        self.LabelBlackListedIcon.setGeometry(QtCore.QRect(310, 90, 50, 50))
        self.LabelBlackListedIcon.setText("")
        self.LabelBlackListedIcon.setObjectName("LabelBlackListedIcon")
        self.GroupBoxReadingLP = QtWidgets.QGroupBox(LPR_App)
        self.GroupBoxReadingLP.setGeometry(QtCore.QRect(570, 510, 681, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.GroupBoxReadingLP.setFont(font)
        self.GroupBoxReadingLP.setStyleSheet("color: #e4f1fe")
        self.GroupBoxReadingLP.setObjectName("GroupBoxReadingLP")
        self.LabelReadingLPText = QtWidgets.QLabel(self.GroupBoxReadingLP)
        self.LabelReadingLPText.setGeometry(QtCore.QRect(190, 30, 471, 100))
        font = QtGui.QFont()
        font.setPointSize(47)
        self.LabelReadingLPText.setFont(font)
        self.LabelReadingLPText.setText("")
        self.LabelReadingLPText.setObjectName("LabelReadingLPText")
        self.LabelReadingLPIcon = QtWidgets.QLabel(self.GroupBoxReadingLP)
        self.LabelReadingLPIcon.setGeometry(QtCore.QRect(50, 30, 100, 100))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 37, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.LabelReadingLPIcon.setPalette(palette)
        self.LabelReadingLPIcon.setText("")
        self.LabelReadingLPIcon.setObjectName("LabelReadingLPIcon")
        self.GroupBoxWebcamCapture = QtWidgets.QGroupBox(LPR_App)
        self.GroupBoxWebcamCapture.setGeometry(QtCore.QRect(570, 10, 681, 481))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.GroupBoxWebcamCapture.setFont(font)
        self.GroupBoxWebcamCapture.setStyleSheet("color: #e4f1fe")
        self.GroupBoxWebcamCapture.setObjectName("GroupBoxWebcamCapture")
        self.LabelWebcamFrame = QtWidgets.QLabel(self.GroupBoxWebcamCapture)
        self.LabelWebcamFrame.setGeometry(QtCore.QRect(20, 30, 641, 431))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 159, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 159, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 241, 254, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.LabelWebcamFrame.setPalette(palette)
        self.LabelWebcamFrame.setAutoFillBackground(False)
        self.LabelWebcamFrame.setStyleSheet("QLabel {\n"
"    background-color:  #454545;\n"
"}")
        self.LabelWebcamFrame.setText("")
        self.LabelWebcamFrame.setObjectName("LabelWebcamFrame")
        self.GroupBoxMatchingVehicleInfo = QtWidgets.QGroupBox(LPR_App)
        self.GroupBoxMatchingVehicleInfo.setGeometry(QtCore.QRect(570, 680, 681, 231))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.GroupBoxMatchingVehicleInfo.setFont(font)
        self.GroupBoxMatchingVehicleInfo.setStyleSheet("color: #e4f1fe")
        self.GroupBoxMatchingVehicleInfo.setObjectName("GroupBoxMatchingVehicleInfo")
        self.LabelLPHeader = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelLPHeader.setGeometry(QtCore.QRect(30, 40, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.LabelLPHeader.setFont(font)
        self.LabelLPHeader.setObjectName("LabelLPHeader")
        self.LabelBLStatusHeader = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelBLStatusHeader.setGeometry(QtCore.QRect(30, 85, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.LabelBLStatusHeader.setFont(font)
        self.LabelBLStatusHeader.setObjectName("LabelBLStatusHeader")
        self.LabelRegisterStatusHeader = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelRegisterStatusHeader.setGeometry(QtCore.QRect(30, 130, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.LabelRegisterStatusHeader.setFont(font)
        self.LabelRegisterStatusHeader.setObjectName("LabelRegisterStatusHeader")
        self.LabelLPText = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelLPText.setGeometry(QtCore.QRect(230, 40, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelLPText.setFont(font)
        self.LabelLPText.setText("")
        self.LabelLPText.setObjectName("LabelLPText")
        self.LabelBLStatusText = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelBLStatusText.setGeometry(QtCore.QRect(230, 130, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelBLStatusText.setFont(font)
        self.LabelBLStatusText.setText("")
        self.LabelBLStatusText.setObjectName("LabelBLStatusText")
        self.LabelRegisterStatusText = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelRegisterStatusText.setGeometry(QtCore.QRect(230, 90, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.LabelRegisterStatusText.setFont(font)
        self.LabelRegisterStatusText.setText("")
        self.LabelRegisterStatusText.setObjectName("LabelRegisterStatusText")
        self.ButtonAddNewRegistry = QtWidgets.QPushButton(self.GroupBoxMatchingVehicleInfo)
        self.ButtonAddNewRegistry.setGeometry(QtCore.QRect(490, 30, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ButtonAddNewRegistry.setFont(font)
        self.ButtonAddNewRegistry.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ButtonAddNewRegistry.setMouseTracking(True)
        self.ButtonAddNewRegistry.setStyleSheet("background-color: #454545;\n"
"color: #e4f1fe;")
        self.ButtonAddNewRegistry.setAutoDefault(False)
        self.ButtonAddNewRegistry.setDefault(False)
        self.ButtonAddNewRegistry.setFlat(False)
        self.ButtonAddNewRegistry.setObjectName("ButtonAddNewRegistry")
        self.LabelNotificationMesssage = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelNotificationMesssage.setGeometry(QtCore.QRect(70, 180, 391, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.LabelNotificationMesssage.setFont(font)
        self.LabelNotificationMesssage.setText("")
        self.LabelNotificationMesssage.setObjectName("LabelNotificationMesssage")
        self.LabelLabelNotificationMesssageIcon = QtWidgets.QLabel(self.GroupBoxMatchingVehicleInfo)
        self.LabelLabelNotificationMesssageIcon.setGeometry(QtCore.QRect(20, 180, 30, 30))
        self.LabelLabelNotificationMesssageIcon.setText("")
        self.LabelLabelNotificationMesssageIcon.setObjectName("LabelLabelNotificationMesssageIcon")
        self.ButtonAddAsVisitor = QtWidgets.QPushButton(self.GroupBoxMatchingVehicleInfo)
        self.ButtonAddAsVisitor.setGeometry(QtCore.QRect(490, 80, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ButtonAddAsVisitor.setFont(font)
        self.ButtonAddAsVisitor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ButtonAddAsVisitor.setMouseTracking(True)
        self.ButtonAddAsVisitor.setStyleSheet("background-color: #454545;\n"
"color: #e4f1fe;")
        self.ButtonAddAsVisitor.setObjectName("ButtonAddAsVisitor")
        self.ButtonDeleteCurrentRegistry = QtWidgets.QPushButton(self.GroupBoxMatchingVehicleInfo)
        self.ButtonDeleteCurrentRegistry.setGeometry(QtCore.QRect(490, 180, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ButtonDeleteCurrentRegistry.setFont(font)
        self.ButtonDeleteCurrentRegistry.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ButtonDeleteCurrentRegistry.setMouseTracking(True)
        self.ButtonDeleteCurrentRegistry.setStyleSheet("background-color: #454545;\n"
"color: #e4f1fe;")
        self.ButtonDeleteCurrentRegistry.setObjectName("ButtonDeleteCurrentRegistry")
        self.ButtonAddToBlackList = QtWidgets.QPushButton(self.GroupBoxMatchingVehicleInfo)
        self.ButtonAddToBlackList.setGeometry(QtCore.QRect(490, 130, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ButtonAddToBlackList.setFont(font)
        self.ButtonAddToBlackList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ButtonAddToBlackList.setMouseTracking(True)
        self.ButtonAddToBlackList.setStyleSheet("background-color: #454545;\n"
"color: #e4f1fe;")
        self.ButtonAddToBlackList.setObjectName("ButtonAddToBlackList")

        self.retranslateUi(LPR_App)
        QtCore.QMetaObject.connectSlotsByName(LPR_App)

    def retranslateUi(self, LPR_App):
        _translate = QtCore.QCoreApplication.translate
        LPR_App.setWindowTitle(_translate("LPR_App", "Form"))
        self.GroupBoxPreviousPlates.setTitle(_translate("LPR_App", "Önceki Plakalar"))
        self.GroupBoxPassIcons.setTitle(_translate("LPR_App", "Geçiş İkonları"))
        self.LabelRegisteredHeader.setText(_translate("LPR_App", "Kayıtlı"))
        self.LabelUnrecognizedHeader.setText(_translate("LPR_App", "Tanınmayan"))
        self.LabelGuestHeader.setText(_translate("LPR_App", "Misafir"))
        self.LabelBlackListedHeader.setText(_translate("LPR_App", "Kara Liste"))
        self.GroupBoxReadingLP.setTitle(_translate("LPR_App", "Okunan Plaka"))
        self.GroupBoxWebcamCapture.setTitle(_translate("LPR_App", "Kamera Görüntüsü"))
        self.GroupBoxMatchingVehicleInfo.setTitle(_translate("LPR_App", "Eşleşen Kayıt"))
        self.LabelLPHeader.setText(_translate("LPR_App", "Plaka: "))
        self.LabelBLStatusHeader.setText(_translate("LPR_App", "Kayıt Durumu:"))
        self.LabelRegisterStatusHeader.setText(_translate("LPR_App", "Kara Liste Durumu:"))
        self.ButtonAddNewRegistry.setText(_translate("LPR_App", "Yeni Kayıt Ekle"))
        self.ButtonAddAsVisitor.setText(_translate("LPR_App", "Misafir Olarak Ekle"))
        self.ButtonDeleteCurrentRegistry.setText(_translate("LPR_App", "Sil"))
        self.ButtonAddToBlackList.setText(_translate("LPR_App", "Kara Listeye Al"))
